config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  devise_for :users
  resources :applications
  root 'welcome#home'

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user

  has_many :events, dependent: :destroy

  def home_page
    self.events.where(name: "home page").count
  end

  def topics_page
    self.events.where(name: "topics page").count
  end

  def bookmarks_page
    self.events.where(name: "bookmarks page").count
  end

  def users_page
    self.events.where(name: "user page").count
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    application = Application.find_by(url: request.env['HTTP_ORIGIN'])

    if application == nil
      render json: "Unregistered Applicagion", status: :unprocessable_entity
    end

    event = application.events.build(event_params)

    if event.save!
      render json: event, status: :created
    else
      render json: {errors: event.errors }, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    applications_path
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def index
    @applications = Application.all
  end

  def show
    @application = Application.find(params[:id])
    @events = @application.events.group_by(&:name)
  end

  def new
    @application = Application.new
  end

  def create
    @application = current_user.applications.build(application_params)

    if @application.save
      flash[:notice] = "You applications was created"
      redirect_to applications_path
    else
      flash.now[:alert] = "There was a problem, try again"
      render :new
    end
  end

  def edit
    @application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])
    @application.assign_atributes(application_params)

    if @application.save
      flash[:notice] = "Your applications has been updated"
      redirect_to @application
    else
      flash.now[:alert] = "There was an error, try again"
      render :edit
    end
  end

  def destroy
    @application = Application.find(params[:id])

    if @application.destroy
      flash[:notice] = "Application #{@application.url} was deleted"
      redirect_to applications_path
    else
      flash.now[:alert] = "There was an error, try again"
      render :show
    end
  end

  private

  def application_params
    params.require(:application).permit(:url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_form.html.erb
<%= form_for @application do |f| %>
  <div class="form-group">
    <%= f.text_field :url, class: 'form-control', placeholder: "url", autofocus: true %>
  </div>


  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/applications/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", applications_path %></li>
        <li><%= link_to "Reporting", :back %></li> <!-- use JS to capture last app link clicked and return to it. -->
      </ul>
    </div>
  </div>
</nav>

app/views/applications/edit.html.erb
<div class="row down">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Edit Application</h3>
    </div>

    <div class="panel-body">
      <%= render partial: 'applications/form' %>
    </div>
  </div>
</div>

app/views/applications/index.html.erb
<div class="container">
  <div class="row down">
    <div class="col-md-12">
      <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= current_user.email %> applications</h3>
      </div>

      <% @applications.each do |application| %>

        <div class="panel-body">
          <div class="col-sm-6">
            <h4><%= link_to application.url, application %></h4>
          </div>
          <div class="col-sm-6 text-right">
            <%= link_to 'Edit', edit_application_path(application), class: 'btn btn-success'%>
            <%= link_to 'Delete', application, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/applications/new.html.erb
<div class="row down">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Add A New Application</h3>
    </div>

    <div class="panel-body">
      <%= render partial: 'applications/form' %>
    </div>
  </div>
</div>

app/views/applications/show.html.erb
<div class="row">
  <div class="col-xs-3 col-lg-2">
    <div class="panel panel-default side-bar">
      <div class="panel-body">
        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp;<%= link_to 'Dashboard', @application %>
      </div>
      <div class="panel-body">
        <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>&nbsp;<%= link_to 'Charts', href: '#' %>
      </div>
    </div>
  </div>

  <div class="col-xs-9 col-lg-10">
    <h2><%= @application.url %></h2>
    <hr/>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Data Pie Chart</h3>
      </div>
      <div class="panel-body">
        <%= pie_chart @application.events.group(:name).count %>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary show-panel">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <span class="glyphicon glyphicon-user btn btn-primary btn-lg" aria-hidden="true"></span>
            </div>
            <div class="col-xs-9 text-right">
              <div>
                <h3>
                  <%= @application.home_page %>
                </h3>
              </div>
              <div><h4>Home Page</h4>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary show-panel">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <span class="glyphicon glyphicon-send btn btn-primary btn-lg" aria-hidden="true"></span>
            </div>
            <div class="col-xs-9 text-right">
              <div>
                <h3>
                  <%= @application.topics_page %>
                </h3>
              </div>
              <div><h4>Topics Page</h4></div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary show-panel">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <span class="glyphicon glyphicon-send btn btn-primary btn-lg" aria-hidden="true"></span>
            </div>
            <div class="col-xs-9 text-right">
              <div>
                <h3>
                  <%= @application.bookmarks_page %>
                </h3>
              </div>
              <div><h4>Bookmarks</h4></div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="panel panel-primary show-panel">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <span class="glyphicon glyphicon-send btn btn-primary btn-lg" aria-hidden="true"></span>
            </div>
            <div class="col-xs-9 text-right">
              <div>
                <h3>
                  <%= @application.users_page %>
                </h3>
              </div>
              <div><h4>User Pages</h4></div>
            </div>
          </div>
          <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </dvi>
</div>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_jumbo.html.erb
<% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="containers">
      <div class="col-md-offset-6 col-md-6">
        <h2>Knowing your data is power</h2>
        <blockquote>
          "Conversion rates for Arc Reactor sales went up 400% after
           BlocMetrics showed us where we could make improvements."
           <footer>Tony Stark <cite title="Stark Industries">Stark Industries</cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blocmetrics", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path, class: 'navbar-link' %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"</span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New Application", new_application_path, :class => 'navbar-link' %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/nav' %>
  <% if user_signed_in? %>
    <%= render partial: 'applications/nav' %>
  <% end %>
  <%= render partial: 'layouts/flash' %>
  <%= yield :jumbotron %>


  <%= yield %>


</body>
</html>

app/views/welcome/home.html.erb
<%= render partial: 'layouts/jumbo' %>